### ISSUE TITLE
Enabling rec_wysiwyg causes error

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/recserv.uiowa.edu#11]
```bash
The following extensions will be enabled: rec_wysiwyg
Do you really want to continue? (y/n): y
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'format' cannot be null' in [error]
/Users/ajdelaney/acquia/uiowa703/docroot/includes/database/database.inc:2227
Stack trace:
#0 /Users/ajdelaney/acquia/uiowa703/docroot/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /Users/ajdelaney/acquia/uiowa703/docroot/includes/database/database.inc(697): DatabaseStatementBase->execute(Array, Array)
#2 /Users/ajdelaney/acquia/uiowa703/docroot/includes/database/mysql/query.inc(36): DatabaseConnection->query('INSERT INTO
{fi...', Array, Array)
#3 /Users/ajdelaney/acquia/uiowa703/docroot/includes/database/query.inc(1621): InsertQuery_mysql->execute()
#4 /Users/ajdelaney/acquia/uiowa703/docroot/modules/filter/filter.module(225): MergeQuery->execute()
#5 /Users/ajdelaney/acquia/uiowa703/docroot/profiles/sitenow/modules/contrib/features/includes/features.filter.inc(93):
filter_format_save(Object(stdClass))
#6 [internal function]: filter_features_rebuild('rec_wysiwyg', 'filter')
#7 /Users/ajdelaney/acquia/uiowa703/docroot/profiles/sitenow/modules/contrib/features/features.module(597):
call_user_func_array('filter_features...', Array)
#8 /Users/ajdelaney/acquia/uiowa703/docroot/profiles/sitenow/modules/contrib/features/features.module(1003):
features_invoke('filter', 'features_rebuil...', 'rec_wysiwyg')
#9 /Users/ajdelaney/acquia/uiowa703/docroot/profiles/sitenow/modules/contrib/features/features.module(387):
_features_restore('rebuild', Array)
#10 [internal function]: features_modules_enabled(Array)
#11 /Users/ajdelaney/acquia/uiowa703/docroot/includes/module.inc(957): call_user_func_array('features_module...', Array)
#12 /Users/ajdelaney/acquia/uiowa703/docroot/includes/module.inc(516): module_invoke_all('modules_enabled', Array)
#13 /Applications/DevDesktop/tools/vendor/drush/drush/commands/core/drupal/environment_7.inc(143): module_enable(Array)
#14 /Applications/DevDesktop/tools/vendor/drush/drush/commands/pm/pm.drush.inc(1167): drush_module_enable(Array)
#15 [internal function]: drush_pm_enable('rec_wysiwyg')
#16 /Applications/DevDesktop/tools/vendor/drush/drush/includes/command.inc(373): call_user_func_array('drush_pm_enable', Array)
#17 /Applications/DevDesktop/tools/vendor/drush/drush/includes/command.inc(224): _drush_invoke_hooks(Array, Array)
#18 [internal function]: drush_command('rec_wysiwyg')
#19 /Applications/DevDesktop/tools/vendor/drush/drush/includes/command.inc(192): call_user_func_array('drush_command', Array)
#20 /Applications/DevDesktop/tools/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#21 /Applications/DevDesktop/tools/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#22 /Applications/DevDesktop/tools/vendor/drush/drush/drush.php(12): drush_main()
#23 {main}
```

**Comment by adamdelaney** [comment]
This is an issue with exporting text formats. Instead we need to run it in an install or update hook.
